### ISSUE TITLE
XSS?

### ISSUE THREAD

**Issue by Alanz2223** [abrenaut/posio#4]
After some time, at the end of a match it would alert xss (cross site script)?

**Comment by mappum** [comment]
This was me. Posio is vulnerable to cross-site scripting (XSS), I was able to set my name to `<script>alert('xss')</script>`, then whenever my name shows up on the leaderboard the script runs. This can be fixed by escaping all the `<` and `>` characters in user's names (convert them to `:&lt;` and `&gt;`.

I had to make a script to automatically look up each city and answer with the exact coordinates every turn, but that's another story :)

**Comment by nathancahill** [comment]
@mappum u r tru l33t haxx0r

**Comment by abrenaut** [comment]
Fixed by #5
